steps:
  # 프론트엔드 빌드 및 배포
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/f-lab-project-440413/next-client',
      '-f', 'apps/next-client/Dockerfile',
      '.',
      '--build-arg', 'GOOGLE_CLIENT_ID=560997285561-laq7qtne5qfo3uqvm7opijbvdpf05fdb.apps.googleusercontent.com',
      '--build-arg', 'GOOGLE_CLIENT_SECRET=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',
      '--build-arg', 'NEXTAUTH_URL=https://f-lab-project-440413.uc.r.appspot.com',
      '--build-arg', 'NEXTAUTH_SECRET=8b885ddb0a5da1f04784be72e27589c9fbfee22d20f4ef27f063d8ed7d8211bd',
      '--build-arg', 'NEXT_PUBLIC_LOCAL_BACKEND_URL=https://backend-dot-f-lab-project-440413.uc.r.appspot.com'
      '--build-arg', 'NEXT_PUBLIC_KAKAO_MAP_KEY=23090c63da235aab83cf17abbb29bcab'
      '--build-arg', 'DATA_API_KEY=YJ8so8uNR%2FiHv%2FB3FhjsGfy%2BxFhgfB9tv9grEqDfzPkkoWEx8tIiME6UarZefKqWPeHo%2BE3XxrtqA8BH0WOlnQ%3D%3D'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/f-lab-project-440413/next-client']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'app', 'deploy',
      'apps/next-client/app.yaml',
      '--image-url=gcr.io/f-lab-project-440413/next-client'
    ]

  # 백엔드 빌드 및 배포
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/f-lab-project-440413/express-server',
      '-f', 'apps/express-server/Dockerfile',
      '.',
      '--build-arg', 'JWT_SECRET=b1fbf862fe5538e821c12ac9c45c9809f87e685e04ebe183ec061efd5a46820ea779b0d159732465ca36c97a62c4c7305e89df29b859cdabd5161b67548875fb',
      '--build-arg', 'DB_USER=postgres',
      '--build-arg', 'DB_HOST=/cloudsql/f-lab-project-440413:us-central1:postgres',
      '--build-arg', 'DB_NAME=postgres',
      '--build-arg', 'DB_PASSWORD=postgres',
      '--build-arg', 'DB_PORT=5432',
      '--build-arg', 'FRONTEND_URL=https://f-lab-project-440413.uc.r.appspot.com'
      '--build-arg', 'DATA_API_KEY=YJ8so8uNR%2FiHv%2FB3FhjsGfy%2BxFhgfB9tv9grEqDfzPkkoWEx8tIiME6UarZefKqWPeHo%2BE3XxrtqA8BH0WOlnQ%3D%3D'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/f-lab-project-440413/express-server']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'app', 'deploy',
      'apps/express-server/app.yaml',
      '--image-url=gcr.io/f-lab-project-440413/express-server'
    ]

images:
  - 'gcr.io/f-lab-project-440413/next-client'
  - 'gcr.io/f-lab-project-440413/express-server'