steps:
  # 백엔드 빌드 및 배포
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/medi-map-440316/express-server',
      '-f', 'apps/express-server/Dockerfile',
      '.',
      '--build-arg', 'JWT_SECRET=b1fbf862fe5538e821c12ac9c45c9809f87e685e04ebe183ec061efd5a46820ea779b0d159732465ca36c97a62c4c7305e89df29b859cdabd5161b67548875fb',
      '--build-arg', 'DB_USER=postgres',
      '--build-arg', 'DB_HOST=/cloudsql/medi-map-440316:asia-northeast3:postgres',
      '--build-arg', 'DB_NAME=postgres',
      '--build-arg', 'DB_PASSWORD=postgres',
      '--build-arg', 'DB_PORT=5432',
      '--build-arg', 'FRONTEND_URL=https://medi-map-440316.du.r.appspot.com'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/medi-map-440316/express-server']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'app', 'deploy',
      'apps/express-server/app.yaml',
      '--image-url=gcr.io/medi-map-440316/express-server'
    ]

images:
  - 'gcr.io/medi-map-440316/express-server'
