services:
  express-server:
    image: docker_username/express-server
    build:
      context: .
      dockerfile: ./apps/express-server/Dockerfile
    ports:
      - '5000:5000'

  next-client:
    image: docker_username/next-client
    build:
      context: .
      dockerfile: ./apps/next-client/Dockerfile
    ports:
      - '3002:3000'

