version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: crud-api
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" 
    volumes:
      - ../postgres-data:/var/lib/postgresql/data 

  express-server:
    image: henny1105/express-server
    build:
      context: .
      dockerfile: ./apps/express-server/Dockerfile
    ports:
      - '5000:5000'
    environment:
      DB_HOST: crud-api          # PostgreSQL 서비스 이름
      DB_PORT: 5432              # PostgreSQL 포트
      DB_USER: postgres           # PostgreSQL 사용자
      DB_PASSWORD: postgres       # PostgreSQL 비밀번호
      DB_NAME: postgres           # 사용할 데이터베이스 이름

  next-client:
    image: henny1105/next-client
    build:
      context: .
      dockerfile: ./apps/next-client/Dockerfile
    ports:
      - '3000:3000'
