runtime: custom
env: flex
instance_class: F2

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5

env_variables:
  NEXT_PUBLIC_LOCAL_BACKEND_URL: "https://backend-dot-medi-map-449217.uc.r.appspot.com"
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: "projects/109725974101/secrets/NEXT_PUBLIC_LOCAL_BACKEND_URL/versions/latest"
  GOOGLE_CLIENT_ID: "projects/109725974101/secrets/GOOGLE_CLIENT_ID/versions/latest"
  GOOGLE_CLIENT_SECRET: "projects/109725974101/secrets/GOOGLE_CLIENT_SECRET/versions/latest"
  NEXTAUTH_SECRET: "projects/109725974101/secrets/NEXTAUTH_SECRET/versions/latest"
  NEXTAUTH_URL: "projects/109725974101/secrets/NEXTAUTH_URL/versions/latest"
  NEXT_PUBLIC_KAKAO_MAP_KEY: "projects/109725974101/secrets/NEXT_PUBLIC_KAKAO_MAP_KEY/versions/latest"
  DATA_API_KEY: "projects/109725974101/secrets/DATA_API_KEY/versions/latest"

readiness_check:
  app_start_timeout_sec: 600