runtime: custom
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  JWT_SECRET: 'projects/109725974101/secrets/JWT_SECRET/versions/latest'
  DB_USER: 'postgres'
  DB_HOST: '/cloudsql/medi-map-449217:us-central1:postgress'
  DB_NAME: 'postgres'
  DB_PASSWORD: 'postgres'
  DB_PORT: 5432
  FRONTEND_URL: 'https://medi-map-chi.vercel.app'
  DATA_API_KEY: 'projects/109725974101/secrets/DATA_API_KEY/versions/latest'

beta_settings:
  cloud_sql_instances: 'medi-map-449217:us-central1:postgress'

readiness_check:
  app_start_timeout_sec: 600

service: backend