runtime: custom
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  JWT_SECRET: 'projects/109725974101/secrets/JWT_SECRET/versions/latest'
  DB_USER: 'postgres'
  DB_HOST: '/cloudsql/medi-map-449217:us-central1:postgres'
  DB_NAME: 'postgres'
  DB_PASSWORD: 'projects/109725974101/secrets/DB_PASSWORD/versions/latest'
  DB_PORT: 5432
  FRONTEND_URL: 'https://f-lab-project-440413.uc.r.appspot.com'
  DATA_API_KEY: 'projects/109725974101/secrets/DATA_API_KEY/versions/latest'

beta_settings:
  cloud_sql_instances: "f-lab-project-440413:us-central1:postgres"

readiness_check:
  app_start_timeout_sec: 600

service: backend