name: publish-docker-images

on:
  push:
    branches:
      - 'feature/docker-test'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 3. 현재 날짜 가져오기
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y_%m_%d_%H_%M')" >> $GITHUB_ENV

      # 4. DockerHub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # 5. express-server 이미지 빌드 및 푸시
      - name: Build and Push express-server Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/express-server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/express-server:${{ env.DATE }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/express-server:latest
          cache-from: type=gha,scope=express-server
          cache-to: type=gha,mode=max,scope=express-server
          build-args: |
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            DB_USER=${{ secrets.DB_USER }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_PORT=${{ secrets.DB_PORT }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}

      # 6. next-client 이미지 빌드 및 푸시
      - name: Build and Push next-client Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/next-client/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/next-client:${{ env.DATE }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/next-client:latest
          cache-from: type=gha,scope=next-client
          cache-to: type=gha,mode=max,scope=next-client
          build-args: |
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXT_PUBLIC_LOCAL_BACKEND_URL=${{ secrets.NEXT_PUBLIC_LOCAL_BACKEND_URL }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}