name: publish-docker-images

on:
  push:
    branches:
      - 'feature/docker-test'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y_%m_%d_%H_%M')" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Cache Docker layers for express-server
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-express-server-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-express-server-

      - name: Build express-server Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/express-server/Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/express-server:${{ env.date }}
          cache-from: type=gha,scope=express-server
          cache-to: type=gha,mode=max,scope=express-server
          build-args: |
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            DB_USER=${{ secrets.DB_USER }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_PORT=${{ secrets.DB_PORT }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}

      - name: Push express-server Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/express-server:${{ env.date }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/express-server:latest

      - name: Cache Docker layers for next-client
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-next-client-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-next-client-

      - name: Build next-client Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/next-client/Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/next-client:${{ env.date }}
          cache-from: type=gha,scope=next-client
          cache-to: type=gha,mode=max,scope=next-client
          build-args: |
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXT_PUBLIC_LOCAL_BACKEND_URL=${{ secrets.NEXT_PUBLIC_LOCAL_BACKEND_URL }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}

      - name: Push next-client Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/next-client:${{ env.date }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/next-client:latest