name: publish-docker-images

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y_%m_%d_%H_%M')" >> $GITHUB_ENV

      - name: Build express-server Image
        run: docker build -f ./apps/express-server/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/express-server:${{ env.date }} .

      - name: Build next-client Image
        run: docker build -f ./apps/next-client/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/next-client:${{ env.date }} .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Verify Docker login
        run: docker info

      - name: Push express-server Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/express-server:${{ env.date }}

      - name: Push next-client Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/next-client:${{ env.date }}